// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:calories/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(PermissionEntryAdapter());
    registerAdapter(PermissionLevelAdapter());
    registerAdapter(PermissionTypeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(PermissionEntryAdapter());
    registerAdapter(PermissionLevelAdapter());
    registerAdapter(PermissionTypeAdapter());
  }
}
